theme: jekyll-theme-minimal
logo: ../pics/DJI.png
plugins:
  - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%d-%b-%y'